export const EVENTS_MAP = [
  'CREATE_SIGNATURE_IMPORT',
  'CREATE_SIGNATURE_HTML',
  'CREATE_SIGNATURE_TEMPLATE',
  'EDIT_SIGNATURE_IMPORT',
  'EDIT_SIGNATURE_HTML',
  'EDIT_SIGNATURE_TEMPLATE',
  'DELETE_SIGNATURE_IMPORT',
  'DELETE_SIGNATURE_HTML',
  'DELETE_SIGNATURE_TEMPLATE',
];
